version: '3.9'

services:
  frontend-vue-build:
    build:
      context: .
      dockerfile: apps/frontend-vue/Dockerfile
    image: frontend-vue-build
    command: ['true']

  backend:
    build:
      context: .
      dockerfile: apps/backend-fastify/Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        ECWID_STORE_ID: ${ECWID_STORE_ID}
        ECWID_TOKEN: ${ECWID_TOKEN}
    image: backend-fastify
    ports:
      - '8000:8000'
    depends_on:
      - frontend-vue-build
      - postgres
    env_file:
      - ./apps/backend-fastify/.env
    command: >
      sh -c "
        until pg_isready -h postgres -p 5432; do
          echo 'Waiting for Postgres...'; sleep 2;
        done &&
        yarn prisma migrate dev --name init &&
        yarn generate-settings &&
        yarn start
      "

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 231289
      POSTGRES_DB: EcwidPostgresDB
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend-vue-settings:
    build:
      context: .
      dockerfile: apps/frontend-vue-settings/Dockerfile
    image: frontend-vue-settings-dev
    ports:
      - '3333:3333'
    working_dir: /app/apps/frontend-vue-settings
    command: ['yarn', 'preview', '--port', '3333', '--host', '0.0.0.0']

volumes:
  postgres-data:
